export const listTech = [
  { name: 'Nextjs 14 - App router', link: 'https://nextjs.org/docs' },
  { name: 'Next Auth v4', link: 'https://next-auth.js.org/' },
  { name: 'Prisma', link: 'https://www.prisma.io/' },
  { name: 'MongoDB', link: 'https://www.mongodb.com/' },
  { name: 'React 18', link: 'https://react.dev/learn' },
  { name: 'Mantine - V7', link: 'https://mantine.dev/' },
  { name: 'Tanstack - V5', link: 'https://tanstack.com/query/latest/docs/react/overview' },
  { name: 'Tailwindcss - V3', link: 'https://tailwindcss.com/docs/installation' },
  { name: 'clsx', link: 'https://www.npmjs.com/package/clsx' },
  { name: 'dayjs', link: 'https://www.npmjs.com/package/dayjs' },
  { name: 'mantine-react-table', link: 'https://v2.mantine-react-table.com/' },
  { name: 'rettier-plugin-organize-imports', link: 'https://www.npmjs.com/package/prettier-plugin-organize-imports' },
  { name: 'react-countup', link: 'https://www.npmjs.com/package/react-countup' },
  { name: 'zod', link: 'https://zod.dev/' },
  { name: 'react-hook-form - v7', link: 'https://react-hook-form.com/get-started' },
];
